### PR TITLE
new file should not be merged

### PR DESCRIPTION
**Pull request by tommilligan**

### CODE REVIEW

**Comment by tommilligan** [comment]
prowl config

**Comment by tommilligan** [comment]
prowl status

**Comment by tommilligan** [comment]
prowl status

**Comment by tommilligan-plutoflume** [comment]
prowl config

**Comment by tommilligan-plutoflume** [comment]
prowl config

**Comment by tommilligan-plutoflume** [comment]
^ should not respond as no config

**Comment by tommilligan-plutoflume** [comment]
now readded config

**Comment by tommilligan-plutoflume** [comment]
prowl config

**Pull request merged**
