### PR TITLE
Updated bump script

### PR DESCRIPTION
**Pull request by tommilligan**
For clarity

### CODE REVIEW

**Comment by tommilligan** [comment]
prowl config

**Comment by tommilligan** [comment]
prowl config

**Comment by tommilligan** [comment]
prowl config

**Comment by tommilligan** [comment]
prowl config

**Comment by tommilligan** [comment]
prowl config

**Comment by tommilligan** [comment]
prowl config

**Comment by tommilligan** [comment]
prowl config

**Comment by ghost** [comment]
Prowl config for this PR:
```json
{
  "reviewers": [
    null,
    null
  ]
}
```

**Comment by tommilligan** [comment]
prowl config

**Comment by ghost** [comment]
Prowl config for this PR:
```json
{
  "reviewers": [
    "tommilligan"
  ]
}
```

**Comment by tommilligan** [comment]
prowl config

**Comment by tommilligan** [comment]
prowl status

**Comment by tommilligan** [comment]
prowl status

**Review by tommilligan-plutoflume — APPROVED** [review]

**Review by tommilligan-plutoflume — APPROVED** [review]

**Comment by ghost** [comment]
PR is ready for merge

**Comment by tommilligan-plutoflume** [comment]
prowl config

**Pull request merged**
