### PR TITLE
Testing dry_run capabilities

### PR DESCRIPTION
**Pull request by tommilligan**

### CODE REVIEW

**Comment by tommilligan** [comment]
prowl status

**Comment by tommilligan** [comment]
prowl status

**Comment by tommilligan** [comment]
prowl merge

**Comment by tommilligan-plutoflume** [comment]
prowl status

**Comment by ghost** [comment]
This PR is not ready for merge, due to the following reasons:
- PR is labelled as in progress

**Comment by tommilligan** [comment]
prowl status

**Comment by tommilligan** [comment]
prowl status

**Comment by tommilligan** [comment]
prowl status

**Comment by tommilligan** [comment]
prowl status

**Comment by tommilligan** [comment]
prowl touch

**Pull request closed without merging**
