### PR TITLE
Admended readme

### PR DESCRIPTION
**Pull request by tommilligan**
Pls approve to merge markdown files

### CODE REVIEW

**Comment by tommilligan** [comment]
prowl status

**Comment by tommilligan** [comment]
prowl status

**Comment by tommilligan** [comment]
prowl status

**Comment by tommilligan** [comment]
prowl config

**Review by tommilligan-plutoflume — COMMENTED** [review]
not sure I can approve this yet?

**Review by tommilligan-plutoflume — APPROVED** [review]

**Review by tommilligan-plutoflume — APPROVED** [review]

**Review by tommilligan-plutoflume — APPROVED** [review]

**Comment by tommilligan-plutoflume** [comment]
prowl status

**Comment by tommilligan-plutoflume** [comment]
prowl config

**Comment by tommilligan-plutoflume** [comment]
prowl status

**Comment by tommilligan-plutoflume** [comment]
prowl status

**Comment by tommilligan-plutoflume** [comment]
prowl status

**Comment by tommilligan-plutoflume** [comment]
prowl status

**Review by tommilligan-plutoflume — APPROVED** [review]

**Review by tommilligan-plutoflume — APPROVED** [review]

**Pull request merged**
